# Book settings
title: Programando la Historia
author: Claudio Rojas Monsalves
logo: Original.png
execute:
  execute_notebooks: 'off'
latex:
  latex_documents:
    targetname: book.tex
bibtex_bibfiles:
  - references.bib
sphinx:
  config:
    bibtex_reference_style: author_year
    copyright: "2025 Claudio Rojas Monsalves"
repository:
  url: https://github.com/ClaudioRojasMon/apuntes_2025
  path_to_book: .
  branch: main
html:
  use_issues_button: true
  use_repository_button: true
